security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MANAGER:
            - ROLE_USER
            - ROLE_APP_ADMIN
            - ROLE_APP_ADMIN_ORDERED_LIST
            - ROLE_APP_ADMIN_ORDERED_VIEW
            - ROLE_APP_ADMIN_ORDERED_EDIT
            - ROLE_APP_ADMIN_ORDERED_CREATE
            - ROLE_APP_ADMIN_ORDERED_DELETE

            - ROLE_APP_ADMIN_PRODUCT_LIST
            - ROLE_APP_ADMIN_PRODUCT_VIEW
            - ROLE_APP_ADMIN_PRODUCT_EDIT
            - ROLE_APP_ADMIN_PRODUCT_CREATE
            - ROLE_APP_ADMIN_PRODUCT_DELETE

            - ROLE_APP_ADMIN_ORDERED_ITEM_LIST
            - ROLE_APP_ADMIN_ORDERED_ITEM_VIEW
            - ROLE_APP_ADMIN_ORDERED_ITEM_EDIT
            - ROLE_APP_ADMIN_ORDERED_ITEM_CREATE
            - ROLE_APP_ADMIN_ORDERED_ITEM_DELETE

            - ROLE_APP_ADMIN_INVOICE_LIST
            - ROLE_APP_ADMIN_INVOICE_VIEW
            - ROLE_APP_ADMIN_INVOICE_EDIT
            - ROLE_APP_ADMIN_INVOICE_CREATE
            - ROLE_APP_ADMIN_INVOICE_DELETE
        ROLE_ADMIN:
            - ROLE_MANAGER

            - ROLE_APP_ADMIN_USER_LIST
            - ROLE_APP_ADMIN_USER_VIEW
            - ROLE_APP_ADMIN_USER_EDIT
            - ROLE_APP_ADMIN_USER_DELETE

            - ROLE_APP_ADMIN_BUDGET_LIST
            - ROLE_APP_ADMIN_BUDGET_VIEW
            - ROLE_APP_ADMIN_BUDGET_EDIT
            - ROLE_APP_ADMIN_BUDGET_CREATE
            - ROLE_APP_ADMIN_BUDGET_DELETE

            - ROLE_APP_ADMIN_TYPE_LIST
            - ROLE_APP_ADMIN_TYPE_VIEW
            - ROLE_APP_ADMIN_TYPE_EDIT
            - ROLE_APP_ADMIN_TYPE_CREATE
            - ROLE_APP_ADMIN_TYPE_DELETE

            - ROLE_APP_ADMIN_PROVIDER_LIST
            - ROLE_APP_ADMIN_PROVIDER_VIEW
            - ROLE_APP_ADMIN_PROVIDER_EDIT
            - ROLE_APP_ADMIN_PROVIDER_CREATE
            - ROLE_APP_ADMIN_PROVIDER_DELETE

            - ROLE_APP_ADMIN_CONFIG_VIEW
            - ROLE_APP_ADMIN_CONFIG_LIST

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN

            - ROLE_APP_ADMIN_CONFIG_LIST
            - ROLE_APP_ADMIN_CONFIG_VIEW
            - ROLE_APP_ADMIN_CONFIG_EDIT
            - ROLE_APP_ADMIN_CONFIG_CREATE
            - ROLE_APP_ADMIN_CONFIG_DELETE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_MANAGER }