# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Managers
    ordered.manager:
        class: AppBundle\Manager\OrderedManager
        arguments: [@doctrine.orm.entity_manager]

    # Services
        ordered.service:
            class: AppBundle\Service\OrderedService
            arguments: [@doctrine.orm.entity_manager]
