services:
    app.admin.type:
        class: AppBundle\Admin\TypeAdmin
        arguments: [~, AppBundle\Entity\Type, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Type }
