services:
    app.admin.type:
        class: AppBundle\Admin\TypeAdmin
        arguments: [~, AppBundle\Entity\Type, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Type }

    app.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Product }

    app.admin.ordered:
        class: AppBundle\Admin\OrderedAdmin
        arguments: [~, AppBundle\Entity\Ordered, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Ordered }

    app.admin.ordered_item:
        class: AppBundle\Admin\OrderedItemAdmin
        arguments: [~, AppBundle\Entity\OrderedItem, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: OrderedItem }
